include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_required_param: warning # treat missing required parameters as a warning (not a hint)
    missing_return: warning # treat missing returns as a warning (not a hint)
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    # these rules are documented on and in the same order as
    # the Dart Lint rules page to make maintenance easier
    # https://github.com/dart-lang/linter/blob/master/example/all.yaml
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catching_errors
    - avoid_classes_with_only_static_members
    - avoid_double_and_int_checks
    - avoid_field_initializers_in_const_classes
    - avoid_final_parameters
    - avoid_implementing_value_types
    - avoid_positional_boolean_parameters
    - avoid_returning_null
    - avoid_returning_null_for_future
    - avoid_returning_this
    - avoid_setters_without_getters
    - avoid_slow_async_io
    - avoid_type_to_string
    - avoid_types_on_closure_parameters
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - cancel_subscriptions
    - cast_nullable_to_non_nullable
    - close_sinks
    - do_not_use_environment
    - flutter_style_todos
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - no_leading_underscores_for_library_prefixes
    - no_runtimeType_toString
    - noop_primitive_operations
    - null_check_on_nullable_type_parameter
    - omit_local_variable_types
    - one_member_abstracts
    - package_api_docs
    - prefer_asserts_in_initializer_lists
    - prefer_final_locals
    - prefer_if_elements_to_conditional_expressions
    - prefer_interpolation_to_compose_strings
    - prefer_null_aware_method_calls
    - prefer_single_quotes
    - sort_child_properties_last
    - sort_pub_dependencies
    - sort_unnamed_constructors_first
    - test_types_in_equals
    - throw_in_finally
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_lambdas
    - unnecessary_null_aware_assignments
    - unnecessary_parenthesis
    - unnecessary_statements
    - use_string_buffers
    - use_super_parameters

