name: backgammon
description: Backgammon Flame game
version: 0.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  flame: ^1.8.1
  flame_riverpod: ^4.0.0+2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/images/